name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    env:
      DJANGO_SECRET_KEY: testsecretkey
      DEBUG: 1

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt
      working-directory: .  

    - name: Run migrations
      run: python manage.py migrate
      working-directory: .

